// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bug': string;
  'dark': string;
  'dragon': string;
  'electric': string;
  'fairy': string;
  'fighting': string;
  'fire': string;
  'flying': string;
  'ghost': string;
  'gosth': string;
  'grass': string;
  'ground': string;
  'ice': string;
  'img': string;
  'info': string;
  'name': string;
  'normal': string;
  'picture': string;
  'poison': string;
  'psychic': string;
  'rock': string;
  'root': string;
  'stat': string;
  'stat_title': string;
  'stat_value': string;
  'stats': string;
  'type': string;
  'types': string;
  'water': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
